version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

db:
  image: postgres
  restart: always
  environment:
    POSTGRES_NAME: ${{ secrets.DB_NAME }}
    POSTGRES_USER: ${{ secrets.DB_USER }}
    POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
