version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${ BOT_TOKEN }
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: ${ DB_NAME }
      DB_USER: ${ DB_USER }
      DB_PASS: ${ DB_PASS }

db:
  image: postgres
  restart: always
  environment:
    POSTGRES_NAME: ${ DB_NAME }
    POSTGRES_USER: ${ DB_USER }
    POSTGRES_PASSWORD: ${ DB_PASS }
